name: git-fame
on: [push]
jobs:
  rspec:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ruby: ["2.7.5", "3.0.3", "3.1.0"]
        os: ["ubuntu-latest", "macos-latest"]
    steps:
    - uses: actions/checkout@v2
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - run: bundle exec rubocop
    - run: bundle exec rspec --format RSpec::Github::Formatter --force-color
